[package]
name = "busca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
similar = "2.2.1"
term_grid = "0.2.0"
walkdir = "2.3.3"
