[package]
name = "busca"
version = "1.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.2.4", features = ["derive"] }
console = "0.15.5"
glob = "0.3.1"
indicatif = { version = "0.17.3", features = ["rayon"] }
inquire = "0.6.1"
rayon = "1.7.0"
similar = { version = "2.2.1", features = ["inline"] }
term_grid = "0.2.0"
walkdir = "2.3.3"
