[package]
name = "busca"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
console = "0.15.5"
indicatif = "0.17.3"
inquire = "0.6.1"
rayon = "1.7.0"
similar = { version = "2.2.1", features = ["inline"] }
term_grid = "0.2.0"
walkdir = "2.3.3"
