name: Python Bindings

on: push

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Python environment
        run: |
          python -m venv ./python_venv
          source python_venv/bin/activate
          pip install -r python_requirements.txt
      - run: maturin develop --release
      - run: python python/test.py

