name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-clippy:
    name: Build and Clippy
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
      - run: cargo clippy -- -D warnings

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download testing comprehensive repo
        run: |
          git clone https://github.com/Python-World/python-mini-projects.git sample-comprehensive
          cd sample-comprehensive
          git reset --hard e0cfd4b0fe5e0bb4d443daba594e83332d5fb720
          rm -r .github
          cd -
      - run: cargo test
  
  python-test:
    name: Python Test
    # needs: [build-clippy, test]
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Python environment
        run: |
          python -m venv ./python_venv
          source python_venv/bin/activate
          pip install -r python_requirements.txt
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          maturin develop --release
      - uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
      - run: python python/test.py
